camera_info:
  ros__parameters:
    width: 640
    height: 480
    distortion_model: plumb_bob
    d: [0.0, 0.0, 0.0, 0.0, 0.0]
    k: [554.256, 0.0, 320.5,
        0.0, 554.256, 240.5,
        0.0, 0.0, 1.0]
    r: [1.0, 0.0, 0.0,
        0.0, 1.0, 0.0,
        0.0, 0.0, 1.0]
    p: [554.256, 0.0, 320.5, 0.0,
        0.0, 554.256, 240.5, 0.0,
        0.0, 0.0, 1.0, 0.0]

